### PR TITLE
Sudan South regions first intercomparison + template

### PR DESCRIPTION
**Pull request by ivanzvonkov**
image

Only uses test points so it is comparable to the LSTM metrics (below) however this results in very large standard errors.
```
"test_metrics": {
            "accuracy": 0.8429,
            "f1_score": 0.4762,
            "precision_score": 0.4545,
            "recall_score": 0.5,
            "roc_auc_score": 0.8113
        },
```

### CODE REVIEW

**Comment by ivanzvonkov** [comment]
@Gedeon-m-gedus I also created instructions for generating this notebook in the wiki: https://github.com/nasaharvest/crop-mask/wiki/Intercomparison-Accuracy-Assessment#4-push-new-intercomparison-notebook-to-github

@hannah-rae the GEE script at the bottom of the notebook currently doesn't work because the admin zone is not properly specified, could you share the admin zone code from that Sudan GEE app?

Also, `geemap.ee_to_gdf(extracted)` failed with `internal error` for `worldcover-v200` so I skipped it for simplicity for now.

**Comment by Gedeon-m-gedus** [comment]
> @Gedeon-m-gedus I also created instructions for generating this notebook in the wiki: https://github.com/nasaharvest/crop-mask/wiki/Intercomparison-Accuracy-Assessment#4-push-new-intercomparison-notebook-to-github
> 
> @hannah-rae the GEE script at the bottom of the notebook currently doesn't work because the admin zone is not properly specified, could you share the admin zone code from that Sudan GEE app?
> 
> Also, `geemap.ee_to_gdf(extracted)` failed with `internal error` for `worldcover-v200` so I skipped it for simplicity for now.

@ivanzvonkov the crop proportion seems to be low, I was discussing with Hannah about how we could increase positive labels (we can discuss this tomorrow during our scheduled call).

Regarding the RoIs boundary, I think they are fetched from FAO
```
var rois = ee.FeatureCollection("FAO/GAUL/2015/level1")
            .filter(ee.Filter.inList('ADM1_NAME', 
                                     ['Gadaref', 
                                      'Western Darfur',
                                      'Southern Darfur',
                                      'Al Jazeera']));
```

**Comment by ivanzvonkov** [comment]
Thanks @Gedeon-m-gedus I've updated the notebook so that the GEE script includes that ROI

**Comment by Gedeon-m-gedus** [comment]
@ivanzvonkov I realized that the FAO boundaries are wrong! here is the correct boundaries: https://code.earthengine.google.com/?asset=projects/ee-gmuhawenayo/assets/rois

I created a PR for it https://github.com/nasaharvest/crop-mask/pull/363

**Pull request merged**
