### PR TITLE
Fixes to area estimation functions

### PR DESCRIPTION
**Pull request by hannah-rae**
This PR fixes a few issues that were breaking the area estimation pipeline in the current main branch

### CODE REVIEW

**Comment by hannah-rae** [comment]
I added the ability to specify the admin2 boundary name instead of just the admin1. 

@ivanzvonkov I think you spoke with @bmunsh about the accuracy of different admin boundary layers. Do you think the GADM boundaries ok? I am guessing it's better than NE. We can make the change everywhere from NE to GADM if you think so using this code.

Note I also need to update the integration test to load osgeo in the environment and use the new boundaries.

**Comment by hannah-rae** [comment]
@ivanzvonkov made the updates we discussed after merging the other PR that updated the intercomparison code.

pre-commit check is failing because it doesn't want me to use bare except; I need to re-create the error to get the specific error code (which results from attempting to sample an area that is out of bounds of the map). I can try to get to that later today but may be tomorrow

**Review by ivanzvonkov — APPROVED** [review]
LGTM after pre-commit fix.
Will let @adebowaledaniel comment on the area utils updates.

**Review by adebowaledaniel — APPROVED** [review]
I've tested the new additions, LGTM!

**Pull request merged**
