### PR TITLE
Created new dataset North Uganda 2020

### PR DESCRIPTION
**Pull request by yashgadhiya10**
North Uganda 2020

### CODE REVIEW

**Comment by yashgadhiya10** [comment]
@ivanzvonkov - When the data pipeline check is initiated, there is an error related to micromamba setup which is failing the check. Let us know on how to fix this.

**Comment by yashgadhiya10** [comment]
@adebowaledaniel - we are facing some micromamba related errors in our data-pipeline. Your help would be appreciated in moving ahead with this issue.

**Comment by ivanzvonkov** [comment]
Hey @yashgadhiya10 sorry for the delayed response.
I've been dealing with the micromamba issue and a host of other issues here: https://github.com/nasaharvest/crop-mask/pull/406
Basically many things that crop-mask depended on: micromamba, GEE Sentinel-2 collection in OpenMapFlow, xarray, we're recently deprecated and that has caused some issues. I'm finishing up a fix today.

**Comment by ivanzvonkov** [comment]
Still dealing with OpenMapFlow issue: https://github.com/nasaharvest/openmapflow/actions/runs/11941328078/job/33285918436

**Comment by ivanzvonkov** [comment]
Fixed OpenMapFlow issue, now exporting new Senegal data and fixing area test issue, I think it has something to do with GDAL here: https://github.com/nasaharvest/crop-mask/pull/406

**Comment by ivanzvonkov** [comment]
@yashgadhiya10 Okay, the data pipeline + all tests (except area) are working now. The data will take a day or so to get from Google Earth Engine

**Review by ivanzvonkov — CHANGES_REQUESTED** [review]
@yashgadhiya10 There's a dataset duplicates test failure here. 
This is because you've added samples from:
- ceo-UNHCR-North-Uganda-Feb-2019---Feb-2020-(Set-1)-sample-data-2024-10-01.csv
- ceo-UNHCR-North-Uganda-Feb-2019---Feb-2020-(Set-2)-sample-data-2024-10-01.csv

But these samples are already included in `UgandaNorthCEO2019`
- ceo-UNHCR-North-Uganda-Feb-2019---Feb-2020-(Set-1)-sample-data-2024-03-12.csv
- ceo-UNHCR-North-Uganda-Feb-2019---Feb-2020-(Set-2)-sample-data-2024-03-12.csv

What is the differencebetween the data you added and this data that already existed in `UgandaNorthCEO2019`?
cc @MsPixels

**Comment by yashgadhiya10** [comment]
@ivanzvonkov Thank you so much for your help!

So it was just a manual error of placing the 2019-20 csv for 2020 dataset. I fixed the code and made another commit within the same branch. However it seems it is still giving the duplication error. So, I believe we have to remove the already present dataset from openmapflow cloud based on my understanding, do correct me if I am wrong but I am not sure how to remove those.

ceo-UNHCR-North-Uganda-Feb-2019---Feb-2020-(Set-1)-sample-data-2024-10-01.csv
ceo-UNHCR-North-Uganda-Feb-2019---Feb-2020-(Set-2)-sample-data-2024-10-01.csv

So, we won't need these csv files and we can keep the orginial ones.

**Comment by ivanzvonkov** [comment]
@yashgadhiya10 since that dataset was already made in `data/datasets` it wasn't being created again. I've removed it which retriggers the pipeline

**Review by yashgadhiya10 — COMMENTED** [review]
Latest code changes have 2020-21 file as expected.

**Review by yashgadhiya10 — COMMENTED** [review]
Thank you for the clarification, @ivanzvonkov. I can see the latest code having the correct files, so we should be merging the pull request after your approval on this request. Do correct me if I missed anything. Again, thank you!

**Comment by ivanzvonkov** [comment]
Hi @yashgadhiya10, the duplicates test was still failing so I checked the code and noticed that the start date was set to 2019-01-01 while it should be 2020-01-01. I've updated the date and re-triggered the pipeline.

**Review by ivanzvonkov — APPROVED** [review]
Alright, all the data tests finally pass.

**Pull request merged**
