### PR TITLE
New Sudan data

### PR DESCRIPTION
**Pull request by ivanzvonkov**
This PR:
- Adds new Sudan data
- Adds GEE script for generating crop mask for region
- Reruns intercomparison

GEE Script snapshot: https://code.earthengine.google.com/2f5d1453e238e6789f64a0fecabcb3eb

**Note:** Currently exporting the map doesn't work because it's too large. Recommended next step is to either use higher maxPixel parameter or add code to split region in two since middle region is not relevant.

Output:
Screen Shot 2023-11-15 at 3 21 58 PM

Updated intercomparison: https://github.com/nasaharvest/crop-mask/blob/New-Sudan-data/maps/Sudan_Gedaref_Darfur_AlJazirah_2022/intercomparison.ipynb

### Issue 1: ROI specified by GEE code does not match sample allocation
@Gedeon-m-gedus 
GEE code:
```javascript
var border = ee.FeatureCollection("FAO/GAUL/2015/level1").filter(
  ee.Filter.inList('ADM1_NAME', 
    ['Gadaref', 'Western Darfur', 'Southern Darfur', 'Al Jazeera']
  )
);
```
Training pts plotted do not fall within boundaries
image

### Issue 2: Intercomparison has some bug which duplicates samples A LOT
@hannah-rae 
image

### CODE REVIEW

**Comment by ivanzvonkov** [comment]
@Gedeon-m-gedus is it possible to get the ROI from FAO or no?

**Comment by Gedeon-m-gedus** [comment]
> @Gedeon-m-gedus is it possible to get the ROI from FAO or no?

@ivanzvonkov I think the FAO names are kinda different from the names our stakeholders gave. Using FAO names increase the AoI

**Review by hannah-rae — APPROVED** [review]
@ivanzvonkov Good find re: intercomparison duplicates. I thought I've checked before that the number of samples in the csv matches the number of samples in the intercomparison results table, but it has been a while. Have you seen this with other datasets too? I will make a note to look into it for the other datasets too if not.

**Comment by ivanzvonkov** [comment]
I have not paid close enough attention with other datasets, investigating duplicates now and will push fix in another PR. @hannah-rae

**Comment by ivanzvonkov** [comment]
@Gedeon-m-gedus I updated the GEE script to use your provided ROI and some more points are included, however there are still several points in the North East that are not in the ROI. Let me know what you think of this.
Screen Shot 2023-11-16 at 2 22 54 PM

**Comment by ivanzvonkov** [comment]
Going to merge, can update the ROI in separate PR if need be.

**Pull request merged**
