### PR TITLE
Trained new: Ethiopia_Tigray_2020

### PR DESCRIPTION
**Pull request by bhyeh**
Retrained Ethiopia Tigray 2020 model with updated dataset (non-skipping nans) w/ default all training sets . 

"test_metrics": 
"accuracy": 0.7377,
"f1_score": 0.6211,
"precision_score": 0.5142,
"recall_score": 0.7842,
"roc_auc_score": 0.8298

"val_metrics": 
"accuracy": 0.7135,
"f1_score": 0.617,
"precision_score": 0.5063,
"recall_score": 0.7895,
"roc_auc_score": 0.8042

### CODE REVIEW

**Comment by hannah-rae** [comment]
@ivanzvonkov will resolve pre-commit.ci error and check for file conflicts

**Comment by ivanzvonkov** [comment]
pre-commit.ci run

**Review by ivanzvonkov — APPROVED** [review]
Looks good to me! Good to merge and ignore pre-commit.ci failure

If you are curious you can read:
**The story of pre-commit.ci**
I added pre-commit.ci to make linting faster and more automated but alas it has failed..
It has failed not because the code is wrong but because of an environment build issue on the CI side. It worked before on a prior pull request and was pretty neat and so my current suspicion is that it has something to do with how they updated the environment since Christmas (potentially Python version update). The dev team there seems a little too trigger happy about keeping up with the latest versions of everything. I'll fix in separate PR.

**Comment by ivanzvonkov** [comment]
**update**: freezing python version did the trick, pre-commit.ci passes and all is well with the world

**Pull request merged**
